import type { Slot } from '../types';

/** The stable `drp-*` base class for every slot. `styles.css` styles these
 *  classes; consumer `classNames` overrides are merged on top of them. */
export const defaultClassNames: Record<Slot, string> = {
  root: 'drp-root',
  inputGroup: 'drp-input-group',
  inputRoot: 'drp-input-root',
  input: 'drp-input',
  inputStart: 'drp-input-start',
  inputEnd: 'drp-input-end',
  inputInvalid: 'drp-input-invalid',
  inputLabel: 'drp-input-label',
  inputLabelFloating: 'drp-input-label-floating',
  separator: 'drp-separator',
  popover: 'drp-popover',
  panel: 'drp-panel',
  shortcutsPanel: 'drp-shortcuts-panel',
  shortcut: 'drp-shortcut',
  shortcutActive: 'drp-shortcut-active',
  calendar: 'drp-calendar',
  months: 'drp-months',
  month: 'drp-month',
  caption: 'drp-caption',
  dropdowns: 'drp-dropdowns',
  dropdownRoot: 'drp-dropdown-root',
  dropdown: 'drp-dropdown',
  monthDropdown: 'drp-month-dropdown',
  yearDropdown: 'drp-year-dropdown',
  nav: 'drp-nav',
  navButton: 'drp-nav-button',
  chevron: 'drp-chevron',
  monthGrid: 'drp-month-grid',
  weekdays: 'drp-weekdays',
  weekday: 'drp-weekday',
  weeks: 'drp-weeks',
  week: 'drp-week',
  dayCell: 'drp-day-cell',
  day: 'drp-day',
  daySelected: 'drp-day-selected',
  dayRangeStart: 'drp-day-range-start',
  dayRangeEnd: 'drp-day-range-end',
  dayRangeMiddle: 'drp-day-range-middle',
  dayToday: 'drp-day-today',
  dayDisabled: 'drp-day-disabled',
  dayOutside: 'drp-day-outside',
  dayFocused: 'drp-day-focused',
  timePickers: 'drp-time-pickers',
  timePicker: 'drp-time-picker',
  timePickerInputRow: 'drp-time-picker-input-row',
  timePickerSeparator: 'drp-time-picker-separator',
  timePickerInput: 'drp-time-picker-input',
  timePickerArrowRow: 'drp-time-picker-arrow-row',
  timePickerArrowButton: 'drp-time-picker-arrow-button',
  timePickerArrowSpacer: 'drp-time-picker-arrow-spacer',
};
