import type { Slot } from '../types';

/** The stable `drp-*` base class for every slot. `styles.css` styles these
 *  classes; consumer `classNames` overrides are merged on top of them. */
export const defaultClassNames: Record<Slot, string> = {
  root: 'drp-root',
  inputGroup: 'drp-input-group',
  input: 'drp-input',
  inputStart: 'drp-input-start',
  inputEnd: 'drp-input-end',
  inputInvalid: 'drp-input-invalid',
  separator: 'drp-separator',
  popover: 'drp-popover',
  panel: 'drp-panel',
  shortcutsPanel: 'drp-shortcuts-panel',
  shortcut: 'drp-shortcut',
  shortcutActive: 'drp-shortcut-active',
  calendar: 'drp-calendar',
  month: 'drp-month',
  caption: 'drp-caption',
  dropdowns: 'drp-dropdowns',
  dropdown: 'drp-dropdown',
  navButton: 'drp-nav-button',
  weekday: 'drp-weekday',
  week: 'drp-week',
  day: 'drp-day',
  daySelected: 'drp-day-selected',
  dayRangeStart: 'drp-day-range-start',
  dayRangeEnd: 'drp-day-range-end',
  dayRangeMiddle: 'drp-day-range-middle',
  dayToday: 'drp-day-today',
  dayDisabled: 'drp-day-disabled',
  dayOutside: 'drp-day-outside',
  timePicker: 'drp-time-picker',
  timePickerInput: 'drp-time-picker-input',
};
